### ISSUE TITLE
patching netflix 7.79.1 build 14 35169

### ISSUE THREAD

**Issue by xxmcvapourxx** [longseespace/netflix_patch#10]
I've installed apktool > zipalign and jarsigner and jdk and jre installed 

![image](https://user-images.githubusercontent.com/6181895/97577894-eda3b200-19e7-11eb-8335-48ede28bd8e2.png)

im using unbuntu 20.4 but im getting these's errors

**Comment by longseespace** [comment]
What is your apktool version? Looks like the patch is not valid because the outputs were different

**Comment by xxmcvapourxx** [comment]
2.4.1 apktool the latest version

**Comment by longseespace** [comment]
I can see you're patching latest version of netflix (v7.79.1). It won't work. This patch works with older versions (v4.16.3) only.
