### ISSUE TITLE
Cannot connect to Netflix service. Error code : -9.

### ISSUE THREAD

**Issue by CurssedCoffin** [longseespace/netflix_patch#5]
Not works fine for me.
Samsung S7edge, rooted with magisk, security level L1, using custom ROM.
It says I can't connect to Netflix network service. But my network works very well. I'll describe it below.
Before I know this patched version, I was just using a magisk module called "liboemcrypto disabler" which makes me can watch Netflix but not in good quality because this module turns the securite level back to L3. Netflix network connection works very well but I can just watch SD videos, which is sad.
With this module uninstalled, security level L1 now,  I installed the patched version and opened it. And it just says can't connect to Netflix network service after a long time of connection. As said above, my network is pretty good. I just don't know why.
With liboemcrypto disabler installed, I can watch SD videos very well cause I'm L3.
With it uninstalled and the patched version installed, it can't connect to Netflix network connection, but the security level is L1. Error code -9. Can't connect to Netflix service.
Is there anyone had this problem?
Could anyone help me?
Thanks btw.

**Comment by longseespace** [comment]
Don't know if this could help, but my guess is it's using the cache from the previous version. Try this guide to see if it can fix your issue: https://help.netflix.com/en/node/22396

**Comment by CurssedCoffin** [comment]
Thank you alot.
I have tried to reinstall my phone to provide a clean enviroment but it still happens.
There are guys born to not use netflix and i'm one of them haha...
